// mundo-2/livros-react/src/LivroLista.js
import React, {useState, useEffect} from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

const controleLivros = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro = props => {
    const { livro, excluir } = props;
    const nomeEditora = controleEditora.getNomeEditora;

    return (
        <tr>
            <td>
                <p>{livro.titulo}</p>
                <button className="btn btn-danger pull-right" onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora(livro.codEditora)}</td>
            <td>
                <ul>
                {livro.autores.map((autor, index) => (
                    <li key={index}>{autor}</li>
                ))}
                </ul>
            </td>
        </tr>
    );
}

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        setLivros(controleLivros.obterLivros());
        setCarregado(true);
    }, [carregado]);

    const excluir = (codigo) => {
        controleLivros.excluir(codigo);
        setCarregado(false);
    }

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table className="table table-hover">
                <thead className="table-dark">
                    <tr scope="row">
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                {livros.map(livro => (
                    <LinhaLivro
                        key={livro.codigo}
                        livro={livro}
                        excluir={excluir}
                        getNomeEditora={controleEditora.getNomeEditora}
                    />
                ))}
                </tbody>
            </table>
        </main>
    )
}

export default LivroLista;

// mundo-2/livros-angular/src/app/livro-lista/livro-lista.component.ts
import {Component, OnInit} from '@angular/core';
import { Editora } from "../editora";
import { Livro } from "../livro";
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {
  }
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir = (codigo: number) => {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
  <h1 class="mb-4">Catálogo de Livros</h1>
  <table class="table table-hover">
    <thead class="table-dark">
    <tr>
      <th>Título</th>
      <th>Resumo</th>
      <th>Editora</th>
      <th>Autores</th>
    </tr>
    </thead>
    <tbody>
    <tr *ngFor="let livro of livros">
      <td>
        <p>{{livro.titulo}}</p>
        <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
      </td>
      <td>{{livro.resumo}}</td>
      <td>{{obterNome(livro.codEditora)}}</td>
      <td>
        <ul>
          <li *ngFor="let autor of livro.autores">{{ autor }}</li>
        </ul>
      </td>
    </tr>
    </tbody>
  </table>
</main>
