// mundo-2/livros-angular/src/app/livro-dados/livro-dados.component.ts
import {Component, OnInit} from '@angular/core';
import { Livro } from "../livro";
import { Editora } from "../editora";
import { ControleEditoraService } from "../controle-editora.service";
import { ControleLivrosService } from "../controle-livros.service";
import { Router } from "@angular/router";

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router) {
    this.livro = new Livro();
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container mt-5">
  <h1>Cadastro de Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea class="form-control" id="resumo" name="resumo" rows="3" [(ngModel)]="livro.resumo"></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select class="form-control" id="editora" name="editora" required [(ngModel)]="livro.codEditora">
        <option value="" disabled selected>Selecione a Editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores (1 por linha)</label>
      <textarea class="form-control" id="autores" name="autores" rows="3" [(ngModel)]="autoresForm"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// mundo-2/livros-react/src/LivroDados.js
import React, {useEffect, useState} from "react";
import Livro from "./modelo/Livro";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";

const controleLivros = new ControleLivro();
const controleEditora = new ControleEditora();

const LivroDados = props => {
    const opcoes = controleEditora.getEditoras();
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0]);
    const navigate = useNavigate();

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = (event) => {
        event.preventDefault();
        const livro = {
            codigo: 0,
            codEditora: codEditora,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n")
        };
        controleLivros.incluir(livro);
        navigate("/");
    };

    return (
        <main>
            <h2>Dados do Livro</h2>
            <form onSubmit={incluir}>
                <div className="form-group" >
                    <label htmlFor="titulo">Título</label>
                    <input id="titulo" className="form-control" type="text" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                </div>
                <div>
                    <label htmlFor="resumo">Resumo</label>
                    <textarea id="resumo" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
                </div>
                <div>
                    <label htmlFor="editora">Editora</label>
                    <select id="editora" className="form-control" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map((item) => (
                            <option key={item.codEditora} value={item.codEditora}>
                                {item.nome}
                            </option>
                        ))}
                    </select>
                </div>
                <div>
                    <label htmlFor="autores">Autores (1 por linha)</label>
                    <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
                </div>
                <button className="btn btn-primary" type="submit">Salvar Livro</button>
            </form>
        </main>
    )
}
export default LivroDados;
